name: Discord Alert

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send alert to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "GitHub Actions\nRepo: ${{ github.repository }}\nEvento: ${{ github.event_name }}\nAutor: ${{ github.actor }}"
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}
